---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pending-queue
  name: pending-queue
  namespace: schevt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pending-queue
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pending-queue
    spec:
      containers:
        - image: hatiolab/pending-queue:0.0.1
          imagePullPolicy: Always
          name: pending-queue
          ports:
            - containerPort: 9903
          resources:
            requests:
              cpu: 128m
              memory: 128Mi
          securityContext:
            privileged: false
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: pending-queue-cfgmap
      restartPolicy: Always
      serviceAccountName: ""
status:
