kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pending-queue-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Delete
mountOptions:
  - debug
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pending-queue-pv-claim
  namespace: schevt
  labels:
    app: pending-queue
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: pending-queue-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-queue
  namespace: schevt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pending-queue
      tier: postgresql
  template:
    metadata:
      labels:
        app: pending-queue
        tier: postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:13.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pending-queue-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pending-queue-pv
      volumes:
        - name: pending-queue-pv
          persistentVolumeClaim:
            claimName: pending-queue-pv-claim

---
apiVersion: v1
kind: Secret
metadata:
  name: pending-queue-secret
  namespace: schevt
stringData:
  POSTGRES_DB: schevt
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: abcd1234
  PGDATA: /var/lib/postgresql/data/pgdata

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pending-queue
  name: pending-queue-svc
  namespace: schevt
spec:
  type: ClusterIP
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: pending-queue
