apiVersion: v1
kind: Service
metadata:
  labels:
    app: pending-queue
  name: pending-queue-svc
  namespace: schevt
spec:
  type: ClusterIP
  ports:
    - name: "80"
      port: 80
      targetPort: 9903
  selector:
    app: pending-queue
