---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: schevt-mgr
  name: schevt-mgr
  namespace: schevt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schevt-mgr
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: schevt-mgr
    spec:
      containers:
        - image: hatiolab/schevt-mgr:0.4.0
          imagePullPolicy: Always
          name: schevt-mgr
          ports:
            - containerPort: 9902
          resources:
            requests:
              cpu: 128m
              memory: 128Mi
          securityContext:
            privileged: false
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: schevt-mgr-cfgmap
      restartPolicy: Always
      serviceAccountName: ""
status:
