---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scheduler
  name: scheduler
  namespace: hfsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - image: hatiolab/scheduler:0.3.6
          imagePullPolicy: Always
          name: scheduler
          ports:
            - containerPort: 9902
          resources:
            requests:
              cpu: 128m
              memory: 128Mi
          securityContext:
            privileged: false
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: scheduler-cm
      restartPolicy: Always
      serviceAccountName: ""
status:
