kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: schevt-db-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Delete
mountOptions:
  - debug
volumeBindingMode: Immediate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schevt-db-pv-claim
  namespace: schevt
  labels:
    app: schevt-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: schevt-db-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: schevt-db
  namespace: schevt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schevt-db
      tier: postgresql
  template:
    metadata:
      labels:
        app: schevt-db
        tier: postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:13.3
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: schevt-db-secret
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: schevt-db-pv
      volumes:
      - name: schevt-db-pv
        persistentVolumeClaim:
          claimName: schevt-db-pv-claim

---

apiVersion: v1
kind: Secret
metadata:
  name: schevt-db-secret
  namespace: schevt
stringData:
  POSTGRES_DB: schevt
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: abcd1234
  PGDATA: /var/lib/postgresql/data/pgdata


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: schevt-db
  name: schevt-db-svc
  namespace: schevt
spec:
  type: ClusterIP
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: schevt-db

