---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locking-service
  name: locking-service
  namespace: hfsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locking-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: locking-service
    spec:
      containers:
        - image: hatiolab/locking-service:0.4.0
          imagePullPolicy: Always
          name: locking-service
          ports:
            - containerPort: 9902
          resources:
            requests:
              cpu: 128m
              memory: 128Mi
          securityContext:
            privileged: false
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: locking-service-cm
      restartPolicy: Always
      serviceAccountName: ""
status:
