apiVersion: v1
kind: Service
metadata:
  labels:
    app: locking-service
  name: locking-service-svc
  namespace: hfsvc
spec:
  type: ClusterIP
  ports:
    - name: "80"
      port: 80
      targetPort: 9902
  selector:
    app: locking-service
