apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-broker
  name: service-broker-svc
  namespace: svcbroker
spec:
  type: ClusterIP
  ports:
    - name: "80"
      port: 80
      targetPort: 9904
  selector:
    app: service-broker
