---
# local or pg
queue: local
local: ../pending_queue
# pg:
#   host: xxx.xxx.xxx.xxx
#   port: 1234
#   id: username
#   pw: likepassword
#   db: likedbname

# history:
#   host: xxx.xxx.xxx.xxx
#   port: 1234
#   id: username
#   pw: likepassword
#   db: likedbname

