version: '3'
services:
  scheduler:
    image: hatiolab/schevt-mgr:latest
    container_name: scheduler
    volumes:
      - ./scheduler_config.yaml:/app/config.yaml
      - ./scheduler_queue:/app/scheduler_queue
    ports:
      - '9902:9902'

  pending-queue:
    image: hatiolab/pending-queue:latest
    container_name: pendqueue
    volumes:
      - ./pendqueue_config.yaml:/app/config.yaml
      - ./pending_queue:/app/pending_queue
    ports:
      - '9903:9903'

  service-broker:
    image: hatiolab/service-broker:latest
    container_name: svcbroker
    volumes:
      - ./svcbroker_config.yaml:/app/config.yaml
      - ./schbroker_queue:/app/schbroker_queue
    ports:
      - '9904:9904'
